<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Calls</name>
   <tag></tag>
   <elementGuidId>a5d64656-6045-4abe-b9f5-94c1091bbd35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Smses'])[2]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d662f73-93a9-48f9-a288-8c31a5be18a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>dfefb0fd-59a6-464e-b4bf-8778b87447bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-menuitem-link ng-star-inserted</value>
      <webElementGuid>7358f046-2e4a-4d78-a192-3c1d6b72c86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eeab5ee9-8a08-4904-ac99-121e2ec2d3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/players/922826/calls</value>
      <webElementGuid>7e6a3ef8-5703-4377-89e3-faefce829045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calls</value>
      <webElementGuid>73ced541-c0f4-4974-8a1a-cfde3e8b3fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;layout-wrapper layout-sidebar-darkgray layout-static&quot;]/div[@class=&quot;layout-content-wrapper&quot;]/div[@class=&quot;layout-content&quot;]/app-player[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;tabs-wrapper&quot;]/p-tabmenu[@class=&quot;p-element&quot;]/div[@class=&quot;p-tabmenu p-component p-tabmenu-scrollable&quot;]/div[@class=&quot;p-tabmenu-nav-container&quot;]/div[@class=&quot;p-tabmenu-nav-content&quot;]/ul[@class=&quot;p-tabmenu-nav p-reset&quot;]/li[@class=&quot;p-element p-tabmenuitem ng-star-inserted&quot;]/a[@class=&quot;p-ripple p-element p-menuitem-link ng-star-inserted&quot;]</value>
      <webElementGuid>2da4934f-fe75-40d2-906a-b572cc5fe984</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smses'])[2]/following::a[1]</value>
      <webElementGuid>aec6096a-7bc4-4a04-83a3-510abd7cb100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emails'])[1]/following::a[2]</value>
      <webElementGuid>f1e4dfb0-ebbd-4757-a63b-49f1c684a376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corrections'])[1]/preceding::a[1]</value>
      <webElementGuid>975f83ac-8c88-486f-8cbe-fbed06c89601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/players/922826/calls')]</value>
      <webElementGuid>c791c6df-63ef-449e-9d1d-119b9afe592d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>be19b214-2da2-4f48-bea6-12695edc6a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/players/922826/calls' and (text() = 'Calls' or . = 'Calls')]</value>
      <webElementGuid>a3528b30-a332-4aab-95e2-62249dbbd877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
