<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Today_p-radiobutton-box</name>
   <tag></tag>
   <elementGuidId>6a06d9e4-a32d-4b55-bbe5-bda8280bd720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-radiobutton[@id='Today']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Today > div.p-radiobutton.p-component > div.p-radiobutton-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ff725c7-9444-43a6-884f-779896cfd5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-radiobutton-box</value>
      <webElementGuid>ff3d671f-6760-4520-a0e9-7703357692c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Today&quot;)/div[@class=&quot;p-radiobutton p-component&quot;]/div[@class=&quot;p-radiobutton-box&quot;]</value>
      <webElementGuid>4d54b2c9-387d-4fc4-ac1e-ea82f0713560</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-radiobutton[@id='Today']/div/div[2]</value>
      <webElementGuid>6fb719a4-142a-4fb1-b933-96dbdef2b331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/following::div[4]</value>
      <webElementGuid>074b7637-941f-4777-bb93-2ff2a81bd13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yesterday'])[1]/following::div[10]</value>
      <webElementGuid>c3c6175f-ebf5-492b-97c7-5baed483e98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Month'])[1]/preceding::div[1]</value>
      <webElementGuid>7dabd813-9317-4bfe-af47-6f22070ac08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::div[8]</value>
      <webElementGuid>a49e409a-9cc6-474b-b877-b3e4915ac6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/p-radiobutton/div/div[2]</value>
      <webElementGuid>67a10ea1-832c-47b7-b500-f468d5539a1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
