<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign in to your accountEnter your detai_6d8315</name>
   <tag></tag>
   <elementGuidId>f8fe4780-8a37-4e77-a5c2-3a4ddb436948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.login-form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa52b966-fde5-4a30-b732-ec5ae3a7a9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-form</value>
      <webElementGuid>0b2255f1-14b7-48ea-8099-03126c2b6a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in to your accountEnter your details belowLOGIN</value>
      <webElementGuid>042fd8d9-0689-4aac-b26a-b33d2b7bdd38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;recaptcha&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;login-body&quot;]/div[@class=&quot;login-wrapper&quot;]/div[@class=&quot;login-panel&quot;]/form[@class=&quot;login-form-section ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;login-form&quot;]</value>
      <webElementGuid>4380aa60-1fd0-4a51-9ae3-89015135d671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>46b8c8a6-15b8-4827-b21c-0f929463dd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign in to your accountEnter your details belowLOGIN' or . = 'Sign in to your accountEnter your details belowLOGIN')]</value>
      <webElementGuid>df0b7d4e-2ff8-42e0-a8bb-20a6a6a7a7db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
