<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in to your account_p-inputtext p_a34a83</name>
   <tag></tag>
   <elementGuidId>d43637ab-3dfd-4c6f-a1da-0b08d0ff9d5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-element.login-fields.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b8aacdf-8e36-4ca9-b789-3fd393209b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ffb93b30-3ed4-460a-9922-0e56a7271afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>468df963-fa02-4bb8-a3a2-ec09cfc8e943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>0af45a5b-90ba-43f8-b749-81124f4b3db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element login-fields ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>62716c83-a088-48c1-9f94-e6a1a186e879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email or UserName</value>
      <webElementGuid>1ff0eaa4-df0e-495e-b5f0-40ce3554df07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;recaptcha&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;login-body&quot;]/div[@class=&quot;login-wrapper&quot;]/div[@class=&quot;login-panel&quot;]/form[@class=&quot;login-form-section ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;login-form&quot;]/div[@class=&quot;field p-fluid input_field&quot;]/input[@class=&quot;p-inputtext p-component p-element login-fields ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>9214c498-0d02-4128-b8f5-9bb2be590f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>65c845af-26af-4e52-ad87-4b80038b8e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cecb2721-4641-40b9-86f5-65d3d5ab017b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Email or UserName']</value>
      <webElementGuid>b983a15a-9e9d-4f94-bb04-c4ffff4dd8f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
