<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p-button_LOGIN</name>
   <tag></tag>
   <elementGuidId>e7aecc0d-9613-4b13-972c-407ac4689e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to your account'])[1]/following::p-button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p-button.p-element</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p-button</value>
      <webElementGuid>fc12a4e7-8530-4306-a250-d87c464a71d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iconpos</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>3833834c-ad3e-429a-ba2f-2799a3c238f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>styleclass</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0536ad7-2b47-4d04-98cd-296e34e4dc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element</value>
      <webElementGuid>f61ae85d-4bf1-49b5-857a-721690a6eaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>8c9eff53-016c-4340-be9d-d08cc4bbd7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;recaptcha&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;login-body&quot;]/div[@class=&quot;login-wrapper&quot;]/div[@class=&quot;login-panel&quot;]/form[@class=&quot;login-form-section ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;login-form&quot;]/p-button[@class=&quot;p-element&quot;]</value>
      <webElementGuid>ab13ffb4-3201-4c95-9153-8c44530a1cae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to your account'])[1]/following::p-button[1]</value>
      <webElementGuid>a8b80b8f-3b48-4f58-b427-a8f582d1ab6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WE WORK HARD YOU PLAY SAFE'])[1]/preceding::p-button[1]</value>
      <webElementGuid>fb8813f5-0ee7-4b46-a828-82e12db82b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-button</value>
      <webElementGuid>1f1a2e24-bdbe-4398-8375-b4747391cbd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p-button[(text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>ba262fca-41e0-476c-8143-ea7683d0840b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
