<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p-radiobutton_Last 7 Days_FilterDate</name>
   <tag></tag>
   <elementGuidId>21c3b014-02b9-4a6b-a8c5-3e8dbffe18c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-radiobutton[@id='Last7Days']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Last7Days</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p-radiobutton</value>
      <webElementGuid>06175a5b-1160-4af6-8428-668107d8a83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FilterDate</value>
      <webElementGuid>10b232aa-991c-4db9-a3c7-0aeb921cf198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Last7Days</value>
      <webElementGuid>87171a09-85f1-46bd-ad59-2b4fc6f17bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Last7Days</value>
      <webElementGuid>e96e6da8-25ca-4329-a702-76e0fc1a02fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element ng-valid ng-dirty ng-touched</value>
      <webElementGuid>35ac1ae0-59a1-4fb4-9afe-4a3ef378d69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Last7Days&quot;)</value>
      <webElementGuid>22dc9035-9f91-45c6-9a11-4686f0b3380c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p-radiobutton[@id='Last7Days']</value>
      <webElementGuid>5b76fb84-c50f-49d7-961a-1eb88a3bb368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last 7 Days'])[1]/following::p-radiobutton[1]</value>
      <webElementGuid>92c67be3-86b1-4503-a3a5-9cdc4bb79ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last 30 Days'])[1]/following::p-radiobutton[2]</value>
      <webElementGuid>dcae60f6-851e-4e0a-8d21-f7db9885a9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yesterday'])[1]/preceding::p-radiobutton[1]</value>
      <webElementGuid>5fb9d767-1a47-4b56-90bf-57199625e313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::p-radiobutton[2]</value>
      <webElementGuid>e95bdaff-5f29-43e3-b640-fd86c77a4327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/p-radiobutton</value>
      <webElementGuid>8af449c7-950a-4b7f-930a-4abb9d0dbd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p-radiobutton[@name = 'FilterDate' and @id = 'Last7Days']</value>
      <webElementGuid>2bada7e0-1d20-4ae5-b5d4-fd8eaf6a79c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
