<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Drag here to set column labels_ag-icon_e6f641</name>
   <tag></tag>
   <elementGuidId>dcd436de-1658-4048-9956-1eb943675430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ag-group-title-bar-icon.ag-filter-toolpanel-group-title-bar-icon > span.ag-icon.ag-icon-tree-closed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>daf7a710-9b40-490a-8f8b-d7d646aa1711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-icon ag-icon-tree-closed</value>
      <webElementGuid>bed67c85-9094-429d-acf1-d32840d9555c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>20ec7cc4-9afd-4e3c-afb2-4a50a8ec7375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e12269a3-97f0-4948-8407-4e790a5676df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;layout-wrapper layout-sidebar-darkgray layout-static&quot;]/div[@class=&quot;layout-content-wrapper&quot;]/div[@class=&quot;layout-content&quot;]/app-deposits-withdrawals[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;table-wrapper table-wrapper-full-page-height&quot;]/app-ag-table[1]/ag-grid-angular[@class=&quot;ag-theme-alpine&quot;]/div[@class=&quot;ag-root-wrapper ag-layout-normal ag-ltr&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-normal ag-focus-managed&quot;]/div[@class=&quot;ag-side-bar ag-unselectable ag-side-bar-right ag-focus-managed&quot;]/div[@class=&quot;ag-tool-panel-wrapper&quot;]/div[@class=&quot;ag-filter-toolpanel&quot;]/div[@class=&quot;ag-filter-list-panel&quot;]/div[@class=&quot;ag-filter-toolpanel-group-wrapper ag-first-group-visible&quot;]/div[@class=&quot;ag-group ag-filter-toolpanel-group ag-group-item-alignment-stretch ag-filter-toolpanel-group-level-0&quot;]/div[@class=&quot;ag-group-title-bar ag-filter-toolpanel-group-title-bar ag-unselectable ag-filter-toolpanel-group-level-0-header ag-filter-toolpanel-header&quot;]/span[@class=&quot;ag-group-title-bar-icon ag-filter-toolpanel-group-title-bar-icon&quot;]/span[@class=&quot;ag-icon ag-icon-tree-closed&quot;]</value>
      <webElementGuid>0463894d-3ddb-48b7-b819-ca733e0367c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span[2]/span</value>
      <webElementGuid>e3b7b081-b025-49d9-a294-de9af27ae3b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
