<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add User_p-ink</name>
   <tag></tag>
   <elementGuidId>dab781ee-211b-4dcb-9b54-627d1c6abe49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-element.p-ripple.p-button-primary.add-user-btn.p-button.p-component > span.p-ink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f4dbf70-582d-4521-8d0c-d51edcdaf28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ink</value>
      <webElementGuid>84f68194-bca1-49d0-abbc-b94d81617817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;layout-wrapper layout-sidebar-darkgray layout-static&quot;]/div[@class=&quot;layout-content-wrapper&quot;]/div[@class=&quot;layout-content&quot;]/app-users[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;table-wrapper table-wrapper-full-page-height&quot;]/app-filters[1]/p-toolbar[@class=&quot;p-element&quot;]/div[@class=&quot;p-toolbar p-component&quot;]/div[@class=&quot;p-toolbar-group-right ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;p-element p-ripple p-button-primary add-user-btn p-button p-component&quot;]/span[@class=&quot;p-ink&quot;]</value>
      <webElementGuid>53defb39-7bd0-45e2-bce1-ee174466abbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>bb3051b5-6e33-4d87-b734-4ffb9c60c8d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
