<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_p-dropdown-trigger-icon ng-tns-_5cbd61</name>
   <tag></tag>
   <elementGuidId>630a823d-1cf2-47a2-a0f9-98a74995413b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdown[@id='Type']/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-dropdown-trigger-icon.ng-tns-c45-21.pi.pi-chevron-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8b2ed3a5-b02e-47e2-bf0e-b5a19c4db785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-trigger-icon ng-tns-c45-21 pi pi-chevron-down</value>
      <webElementGuid>596afcb4-4adf-4276-8161-4c12b698d709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Type&quot;)/div[@class=&quot;ng-tns-c45-21 p-dropdown p-component&quot;]/div[@class=&quot;p-dropdown-trigger ng-tns-c45-21&quot;]/span[@class=&quot;p-dropdown-trigger-icon ng-tns-c45-21 pi pi-chevron-down&quot;]</value>
      <webElementGuid>ce7be1bf-788e-4a5d-af48-6e35fe56f554</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-dropdown[@id='Type']/div/div[2]/span</value>
      <webElementGuid>c6d19fdc-4ad6-43cd-935c-c11a6e2bb9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p-dropdown/div/div[2]/span</value>
      <webElementGuid>badedb37-e072-4be7-96b6-265d801d6d22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
