<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_p-dropdown-trigger-icon ng-tns-_6d49a1</name>
   <tag></tag>
   <elementGuidId>427b8807-d39a-4f23-ba6e-e31f5ce9e7cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdown[@id='State']/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-dropdown-trigger-icon.ng-tns-c45-23.pi.pi-chevron-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>036b12bf-bff7-4c16-a129-8a5ec56762c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-trigger-icon ng-tns-c45-23 pi pi-chevron-down</value>
      <webElementGuid>a23ecaab-eb6c-4a2d-9494-4d17e0af33a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;State&quot;)/div[@class=&quot;ng-tns-c45-23 p-dropdown p-component&quot;]/div[@class=&quot;p-dropdown-trigger ng-tns-c45-23&quot;]/span[@class=&quot;p-dropdown-trigger-icon ng-tns-c45-23 pi pi-chevron-down&quot;]</value>
      <webElementGuid>cf40ce3c-d91c-473a-bc34-96789763bdb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-dropdown[@id='State']/div/div[2]/span</value>
      <webElementGuid>e8f6169b-6b3a-42b5-9dd3-d2744cd8a10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/p-dropdown/div/div[2]/span</value>
      <webElementGuid>8f8bf6a9-0af7-4fc8-9f4e-536f771eb06d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
