<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_of_p-button-icon icon-fast-search</name>
   <tag></tag>
   <elementGuidId>694a07ac-116c-47c1-925e-42bc22567f8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-quick-search/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-button-icon.icon-fast-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6ee4f93a-79db-4ed9-8c5f-915727f8d691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-icon icon-fast-search</value>
      <webElementGuid>b7a4aa94-8df4-49fb-b77b-b34e0ccd73eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9fc069d1-ac95-4053-9208-c0de6af43dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-quick-search[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;quick-search-layout&quot;]/button[@class=&quot;p-element quick-search-button p-button p-component p-button-icon-only&quot;]/span[@class=&quot;p-button-icon icon-fast-search&quot;]</value>
      <webElementGuid>37217e04-b31f-4df8-9bc2-d55efed34d07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-quick-search/div/button/span</value>
      <webElementGuid>888d1e14-a0ec-4f7e-a84b-8f80e02c320c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
