<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Drag here to set column labels_ag-icon_2ae5c7</name>
   <tag></tag>
   <elementGuidId>6d349ad9-2a7d-4a98-ab57-3a114db14513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ag-group-title-bar-icon.ag-filter-toolpanel-group-title-bar-icon > span.ag-icon.ag-icon-tree-open</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6892400d-2227-4d4d-bf1d-9c70bee9a5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-icon ag-icon-tree-open</value>
      <webElementGuid>97532668-9fa9-459b-9dd4-10f94d953b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b287da3a-1a8a-4fe8-8ad4-78dc3ecca985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>bf8f81a0-055d-4ff7-a656-5e85c5b356a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;layout-wrapper layout-sidebar-darkgray layout-static&quot;]/div[@class=&quot;layout-content-wrapper&quot;]/div[@class=&quot;layout-content&quot;]/app-deposits-withdrawals[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;table-wrapper table-wrapper-full-page-height&quot;]/app-ag-table[1]/ag-grid-angular[@class=&quot;ag-theme-alpine&quot;]/div[@class=&quot;ag-root-wrapper ag-layout-normal ag-ltr&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-normal ag-focus-managed&quot;]/div[@class=&quot;ag-side-bar ag-unselectable ag-side-bar-right ag-focus-managed&quot;]/div[@class=&quot;ag-tool-panel-wrapper&quot;]/div[@class=&quot;ag-filter-toolpanel&quot;]/div[@class=&quot;ag-filter-list-panel&quot;]/div[@class=&quot;ag-filter-toolpanel-group-wrapper ag-first-group-visible&quot;]/div[@class=&quot;ag-group ag-filter-toolpanel-group ag-group-item-alignment-stretch ag-filter-toolpanel-group-level-0&quot;]/div[@class=&quot;ag-group-title-bar ag-filter-toolpanel-group-title-bar ag-unselectable ag-filter-toolpanel-group-level-0-header ag-filter-toolpanel-header&quot;]/span[@class=&quot;ag-group-title-bar-icon ag-filter-toolpanel-group-title-bar-icon&quot;]/span[@class=&quot;ag-icon ag-icon-tree-open&quot;]</value>
      <webElementGuid>5effdd20-346f-4838-b118-59e1b1e28441</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/span</value>
      <webElementGuid>3b9dc5f2-95d8-4169-8f25-3baa208453c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
