<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Partner_p-multiselect-trigger-i_a930a7_1</name>
   <tag></tag>
   <elementGuidId>2b88c459-9253-4126-bce0-6eeab0bae4a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-multiselect-trigger-icon.ng-tns-c70-18.pi.pi-chevron-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>42db48d0-482b-41c2-86a1-69f7506c66b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-trigger-icon ng-tns-c70-18 pi pi-chevron-down</value>
      <webElementGuid>93ff28ee-1c99-4d10-a31c-161ac26b7cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;layout-wrapper layout-sidebar-darkgray layout-static&quot;]/div[@class=&quot;layout-content-wrapper&quot;]/div[@class=&quot;layout-content&quot;]/app-users[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;table-wrapper table-wrapper-full-page-height&quot;]/app-filters[1]/p-toolbar[@class=&quot;p-element&quot;]/div[@class=&quot;p-toolbar p-component&quot;]/div[@class=&quot;p-toolbar-group-left ng-star-inserted&quot;]/app-m-filters[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;filter-sidebar-left filter-sidebar-left-active&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;filters-actions&quot;]/div[@class=&quot;filters-section&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;p-fluid partners ng-star-inserted&quot;]/div[@class=&quot;selected-filter-result active-filter&quot;]/p-multiselect[@class=&quot;p-element p-inputwrapper multiselect-custom ng-tns-c70-18 ng-untouched ng-pristine ng-valid ng-star-inserted p-inputwrapper-focus&quot;]/div[@class=&quot;ng-tns-c70-18 p-multiselect p-component p-multiselect-open&quot;]/div[@class=&quot;ng-tns-c70-18 p-multiselect-trigger&quot;]/span[@class=&quot;p-multiselect-trigger-icon ng-tns-c70-18 pi pi-chevron-down&quot;]</value>
      <webElementGuid>d19b8a43-f2d1-4411-ab66-faf72986e3d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>dccf7f4b-553b-44be-ab1e-226d633154ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
