<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_p-dropdown-trigger-icon ng-tns-_312a07_1</name>
   <tag></tag>
   <elementGuidId>30aea362-6eae-4b98-aac3-1095b4f749c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdown[@id='partnerId']/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-dropdown-trigger-icon.ng-tns-c45-20.pi.pi-chevron-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>26df0181-da4b-4fcd-9666-e1f1eeb12150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-trigger-icon ng-tns-c45-20 pi pi-chevron-down</value>
      <webElementGuid>f767b1b1-4667-4fb1-99e2-41b3660312bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partnerId&quot;)/div[@class=&quot;ng-tns-c45-20 p-dropdown p-component p-dropdown-open&quot;]/div[@class=&quot;p-dropdown-trigger ng-tns-c45-20&quot;]/span[@class=&quot;p-dropdown-trigger-icon ng-tns-c45-20 pi pi-chevron-down&quot;]</value>
      <webElementGuid>52ad3057-7022-40e5-819d-eea25a8e17d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-dropdown[@id='partnerId']/div/div[2]/span</value>
      <webElementGuid>5b4bde0d-4830-44af-b1c8-e7a1ef4349a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p-dropdown/div/div[2]/span</value>
      <webElementGuid>a9e3eb17-0da0-486a-9e0c-78cf989ad239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
