<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save_p-ink</name>
   <tag></tag>
   <elementGuidId>40a22b5b-f0cd-444d-92a4-0ba06e9d96c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[2]/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3c17b8b1-4238-4006-8dbe-975b4d713c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ink</value>
      <webElementGuid>fc4bd862-a9b4-43a2-9f54-9a8d9c63a52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/p-dynamicdialog[@class=&quot;p-element ng-tns-c191-19 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c191-19 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c191-19 dialog-with-footer p-dialog p-dynamic-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;p-dialog-content ng-tns-c191-19&quot;]/app-create-user[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;p-dialog-footer&quot;]/button[@class=&quot;p-element p-ripple p-button-text p-button p-component&quot;]/span[@class=&quot;p-ink&quot;]</value>
      <webElementGuid>c41dbaa7-e910-44e8-a473-d86be2719d4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span[3]</value>
      <webElementGuid>c1c6d203-6671-478e-86bc-975a50a5350d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
