<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cancel_p-ink</name>
   <tag></tag>
   <elementGuidId>fc8a9799-aa33-48a9-9894-cc7a82d1c1d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/button/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-element.p-ripple.p-button-text.p-button-secondary.p-button.p-component > span.p-ink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8c2115fc-92e3-4419-9c0a-d31ca1b2201f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ink</value>
      <webElementGuid>5d05f1cb-fbce-4ec5-93df-54d3a08c79ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/p-dynamicdialog[@class=&quot;p-element ng-tns-c191-19 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c191-19 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c191-19 dialog-with-footer p-dialog p-dynamic-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;p-dialog-content ng-tns-c191-19&quot;]/app-create-user[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;p-dialog-footer&quot;]/button[@class=&quot;p-element p-ripple p-button-text p-button-secondary p-button p-component&quot;]/span[@class=&quot;p-ink&quot;]</value>
      <webElementGuid>db622e4a-d621-4b03-9c45-d608e09c6bd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span[3]</value>
      <webElementGuid>12583777-b99e-48a6-8e53-b1be6ec4bb09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
