<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Provider Settings_p-ink</name>
   <tag></tag>
   <elementGuidId>b7c911a5-8109-415b-baf8-da429f4f0805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-ripple.p-element.p-tabmenu-nav-next.p-tabmenu-nav-btn.p-link.ng-star-inserted > span.p-ink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9fd47168-6ea7-4697-93ee-7978258f8985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ink</value>
      <webElementGuid>4471571f-d0f6-4fd2-9814-3bafb0b963ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;layout-wrapper layout-sidebar-darkgray layout-static&quot;]/div[@class=&quot;layout-content-wrapper&quot;]/div[@class=&quot;layout-content&quot;]/app-player[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;tabs-wrapper&quot;]/p-tabmenu[@class=&quot;p-element&quot;]/div[@class=&quot;p-tabmenu p-component p-tabmenu-scrollable&quot;]/div[@class=&quot;p-tabmenu-nav-container&quot;]/button[@class=&quot;p-ripple p-element p-tabmenu-nav-next p-tabmenu-nav-btn p-link ng-star-inserted&quot;]/span[@class=&quot;p-ink&quot;]</value>
      <webElementGuid>4be96304-3130-4613-bbd1-ff63b50361de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]</value>
      <webElementGuid>165b1157-ec02-4cfb-a2d0-35c02bd10131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
