<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_p-dropdown-trigger-icon ng-tns-_0a8c3c</name>
   <tag></tag>
   <elementGuidId>b0be3bf6-e8b4-4a29-bb7b-82dd327f0450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdown[@id='currencyId']/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-dropdown-trigger-icon.ng-tns-c45-19.pi.pi-chevron-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>89d959b9-b28d-4de4-96b5-b6d986d30985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-trigger-icon ng-tns-c45-19 pi pi-chevron-down</value>
      <webElementGuid>3f9d656e-c412-4b0f-a29d-f3bb6eb6c2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currencyId&quot;)/div[@class=&quot;ng-tns-c45-19 p-dropdown p-component&quot;]/div[@class=&quot;p-dropdown-trigger ng-tns-c45-19&quot;]/span[@class=&quot;p-dropdown-trigger-icon ng-tns-c45-19 pi pi-chevron-down&quot;]</value>
      <webElementGuid>a9567ca0-d3ed-42a8-9d42-6fabc547cf09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-dropdown[@id='currencyId']/div/div[2]/span</value>
      <webElementGuid>ead4ed52-b90d-4772-83aa-5e995a219eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/p-dropdown/div/div[2]/span</value>
      <webElementGuid>75c8a7c8-0ab3-4ba0-ac5e-ab9efd811642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
